---
title: "Student's Weight Status Over Time"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---
```{r set up, include=FALSE}
library(flexdashboard)
library(shiny)
library(readxl)
library(tidyverse)
library(plotly)
library(tidyverse)
library(readxl)
library(plotly)
library(rgdal)
library(maps)
library(devtools)
library(leaflet)
library(maptools)
library(BAMMtools)
library(patchwork)
library(spdep)
library(leafsync)
```

```{r import, include=FALSE}
#data for ranking
original = tibble(
  read.csv("./dataset/Student_Weight_Status_Category_Reporting_Results__Beginning_2010.csv")
) %>%
  janitor::clean_names() %>%
  select(county, percent_overweight_or_obese, percent_healthy_weight)

ranking_df =
  tibble(
  read.csv("./dataset/Student_Weight_Status_Category_Reporting_Results__Beginning_2010.csv")
) %>%
  janitor::clean_names() %>%
  select(-location_code, -area_name, -region) %>% 
  filter(county != "STATEWIDE (EXCLUDING NYC)") %>% 
  mutate(percent_healthy_weight = percent_healthy_weight *100) %>%
  drop_na(percent_overweight_or_obese,percent_healthy_weight) %>% 
  group_by(county, year_reported) %>%
  summarize(oo = mean(percent_overweight_or_obese), hw = mean(percent_healthy_weight))

#data for mapping
fips_code = tibble(
  read.csv("./map_data_jyz/New_York_State_ZIP_Codes-County_FIPS_Cross-Reference.csv")
) %>%
  janitor::clean_names() %>% 
  rename("county" = county_name, "fips" = county_fips) %>% 
  select(county, fips) %>% # only information we need is county name and geolocation
  distinct() %>% 
  mutate(county = toupper(county)) # to swith county name to uppercase

time_map_df = 
  left_join(ranking_df, fips_code, by = "county") %>% 
  mutate(fips = as.character(fips))
```


Students' Weight Map 2010-2019
=====================================

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
year_reported = ranking_df %>% ungroup() %>% distinct(year_reported) %>% pull()

# selectInput widget
selectInput(
  "year_choice", 
  label = h3("Select Year Range"),
  choices = year_reported, selected = "2012-2014")
```

Column {.tabset}
-----------------------------------------------------------------------
### Overweight/Obese Map
```{r}
renderLeaflet({
  
time_map = 
  time_map_df %>%
    filter(
      year_reported == input[["year_choice"]]
    ) 

fips_map = readOGR(dsn = "./map_data_jyz/NYS_Civil_Boundaries_SHP", "Counties")

fips_map@data = left_join(fips_map@data, time_map, by = c("FIPS_CODE" = "fips"))

# CRS setting
fips_map_crs = spTransform(fips_map, CRS("+init=epsg:4326"))
# export the json file
writeOGR(fips_map_crs, './map_data_jyz/fips_time_map_geojson', layer = 'fips_map', driver = 'GeoJSON', overwrite_layer = TRUE)

# format of the label that pops up for each polygon
label_popup_oo = paste0(
  "<strong>FIPS code: </strong>",
  fips_map$FIPS_CODE,
  "<br><strong>County Name: </strong>",
  fips_map$NAME,
  "<br><strong>Percent of Overweight or Obese: </strong>",
  fips_map$oo
)

# get jenks natural break for average
getJenksBreaks(fips_map$oo, 5)

# set bins
percent_oo_bins = c(26,30,34,38,43)

# set pals
percent_oo_pal = colorBin('Reds', bins = percent_oo_bins, na.color = '#d9d9d9')


oo_map = leaflet::leaflet(data = fips_map_crs) %>% 
  addProviderTiles('CartoDB.Positron') %>% 
  addPolygons(fillColor = ~percent_oo_pal(oo),
              fillOpacity = 0.8,
              color = "#BDBDC3",
              weight = 1,
              popup = label_popup_oo,
              highlightOptions = highlightOptions(color = "black", weight = 2,
      bringToFront = TRUE)) %>% 
  addLegend('bottomleft',
            pal = percent_oo_pal,
            values = ~oo,
            title = "The Average Percentage of Students Who were Overweight/Obese",
            opacity = 1)


  })
```

### Healthy Weight Map
```{r}
renderLeaflet({
  
time_map = 
  time_map_df %>%
    filter(
      year_reported == input[["year_choice"]]
    ) 

fips_map = readOGR(dsn = "./map_data_jyz/NYS_Civil_Boundaries_SHP", "Counties")

fips_map@data = left_join(fips_map@data, time_map, by = c("FIPS_CODE" = "fips"))

# CRS setting
fips_map_crs = spTransform(fips_map, CRS("+init=epsg:4326"))
# export the json file
writeOGR(fips_map_crs, './map_data_jyz/fips_time_map_geojson', layer = 'fips_map', driver = 'GeoJSON', overwrite_layer = TRUE)
# format of the label that pops up for each polygon
label_popup_healthy = paste0(
  "<strong>FIPS code: </strong>",
  fips_map$FIPS_CODE,
  "<br><strong>County Name: </strong>",
  fips_map$NAME,
  "<br><strong>Percent of Healthy Weight: </strong>",
  fips_map$hw
)

# get jenks natural break for average
getJenksBreaks(fips_map$hw, 5)

# set bins
percent_healthy_bins <- c(55,60,65,70,81)

# set pals
percent_healthy_pal <- colorBin('Blues', bins = percent_healthy_bins, na.color = '#d9d9d9')

healthy_map = leaflet::leaflet(data = fips_map_crs) %>% 
  addProviderTiles('CartoDB.Positron') %>% 
  addPolygons(fillColor = ~percent_healthy_pal(hw),
              fillOpacity = 0.8,
              color = "#BDBDC3",
              weight = 1,
              popup = label_popup_healthy,
              highlightOptions = highlightOptions(color = "black", weight = 2,
      bringToFront = TRUE)) %>% 
  addLegend('bottomleft',
            pal = percent_healthy_pal,
            values = ~hw,
            title = "The Average Percentage of Students Who Maintained Healthy Weight (2010-2019)",
            opacity = 1)

#sync(oo_map, healthy_map, ncol = 2, sync = "all", sync.cursor = TRUE, no.initial.sync = TRUE)

  })
```

